# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Luca Marchi
url:              http://lucamarchi.me
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

paginate:         3

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
