# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Luca Marchi
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         3
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Pages list
pages_list:
  About:  '/about'
  Archive:  '/archive'
  Feed:     '/atom.xml'
